
package com.aleksandar_simeunovic.forms;

import com.aleksandar_simeunovic.drawing.Drawing;
import com.aleksandar_simeunovic.entities.Ball;
import com.aleksandar_simeunovic.entities.Strela;
import com.aleksandar_simeunovic.model.BModel;
import com.aleksandar_simeunovic.model.IObserver;
import com.aleksandar_simeunovic.model.Model;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Polygon;


public class VModel extends javax.swing.JPanel implements IObserver {

    Model m = BModel.build();

    @Override
    public void ref()
    {
        this.repaint();
    }
    @Override
    protected void paintComponent(Graphics g)
    {
        super.paintComponent(g); 
        Graphics2D g2d = (Graphics2D)g;
        for(Ball b:m.getAllBall())
        {
            Drawing.DrawBall(b,g2d);
        }
        for(Strela strela:m.getAllStrela())
        {
            Drawing.DrawStrela(strela,g2d);
        }
    }
    
    /**
     * Creates new form VModel
     */
    public VModel() {
        initComponents();
        m.addObserver(this);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
